### Variables
# Uncomment the matching @url your current deployment setting!

# Local deployment
@url = http://localhost:3000 

# Local docker deployment
# @url = http://localhost/api


### Login
# @name postLogin
POST {{url}}/auth/login HTTP/1.1
content-type: application/json

{
    "username": "myuser",
    "password": "12345"
}

###

@authToken = {{postLogin.response.body.access_token}}

### Create WebClientService
POST {{url}}/service-docs HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

<@ ./web.client.msadoc.json

### Create ExtractionService
POST {{url}}/service-docs HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

<@ ./extraction.service.msadoc.json

### Create SchedulerService
POST {{url}}/service-docs HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

<@ ./scheduler.service.msadoc.json

### Create TransformationService
POST {{url}}/service-docs HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

<@ ./transformation.service.msadoc.json

### Create LoadService
POST {{url}}/service-docs HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

<@ ./load.service.msadoc.json

### Create NotificationService
POST {{url}}/service-docs HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

<@ ./notification.service.msadoc.json


### Create RestfulQueryService
POST {{url}}/service-docs HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

<@ ./restful-query.service.msadoc.json

### Create GraphQlQueryService
POST {{url}}/service-docs HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

<@ ./graphql-query.service.msadoc.json
