// tslint:disable
/**
 * msdoc server API
 * The msdoc server API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    CreateApiKeyRequestDto,
    CreateApiKeyResponseDto,
    GetApiKeysResponseDto,
    IsApiKeyValidResponseDto,
} from '../models';

export interface ApiKeysControllerCreateApiKeyRequest {
    createApiKeyRequestDto: CreateApiKeyRequestDto;
}

export interface ApiKeysControllerDeleteApiKeyRequest {
    keyId: any;
}

/**
 * no description
 */
export class ApiKeysApi extends BaseAPI {

    /**
     */
    apiKeyTestControllerTestApiKey(): Observable<IsApiKeyValidResponseDto>
    apiKeyTestControllerTestApiKey(opts?: OperationOpts): Observable<AjaxResponse<IsApiKeyValidResponseDto>>
    apiKeyTestControllerTestApiKey(opts?: OperationOpts): Observable<IsApiKeyValidResponseDto | AjaxResponse<IsApiKeyValidResponseDto>> {
        const headers: HttpHeaders = {
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` } : undefined),
        };

        return this.request<IsApiKeyValidResponseDto>({
            url: '/api-keys/test',
            method: 'GET',
            headers,
        }, opts?.responseOpts);
    };

    /**
     */
    apiKeysControllerCreateApiKey({ createApiKeyRequestDto }: ApiKeysControllerCreateApiKeyRequest): Observable<CreateApiKeyResponseDto>
    apiKeysControllerCreateApiKey({ createApiKeyRequestDto }: ApiKeysControllerCreateApiKeyRequest, opts?: OperationOpts): Observable<AjaxResponse<CreateApiKeyResponseDto>>
    apiKeysControllerCreateApiKey({ createApiKeyRequestDto }: ApiKeysControllerCreateApiKeyRequest, opts?: OperationOpts): Observable<CreateApiKeyResponseDto | AjaxResponse<CreateApiKeyResponseDto>> {
        throwIfNullOrUndefined(createApiKeyRequestDto, 'createApiKeyRequestDto', 'apiKeysControllerCreateApiKey');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` } : undefined),
        };

        return this.request<CreateApiKeyResponseDto>({
            url: '/api-keys',
            method: 'POST',
            headers,
            body: createApiKeyRequestDto,
        }, opts?.responseOpts);
    };

    /**
     */
    apiKeysControllerDeleteAllApiKeys(): Observable<void>
    apiKeysControllerDeleteAllApiKeys(opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    apiKeysControllerDeleteAllApiKeys(opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        const headers: HttpHeaders = {
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` } : undefined),
        };

        return this.request<void>({
            url: '/api-keys',
            method: 'DELETE',
            headers,
        }, opts?.responseOpts);
    };

    /**
     */
    apiKeysControllerDeleteApiKey({ keyId }: ApiKeysControllerDeleteApiKeyRequest): Observable<void>
    apiKeysControllerDeleteApiKey({ keyId }: ApiKeysControllerDeleteApiKeyRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    apiKeysControllerDeleteApiKey({ keyId }: ApiKeysControllerDeleteApiKeyRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(keyId, 'keyId', 'apiKeysControllerDeleteApiKey');

        const headers: HttpHeaders = {
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` } : undefined),
        };

        return this.request<void>({
            url: '/api-keys/{keyId}'.replace('{keyId}', encodeURI(keyId)),
            method: 'DELETE',
            headers,
        }, opts?.responseOpts);
    };

    /**
     */
    apiKeysControllerGetAllApiKeys(): Observable<GetApiKeysResponseDto>
    apiKeysControllerGetAllApiKeys(opts?: OperationOpts): Observable<AjaxResponse<GetApiKeysResponseDto>>
    apiKeysControllerGetAllApiKeys(opts?: OperationOpts): Observable<GetApiKeysResponseDto | AjaxResponse<GetApiKeysResponseDto>> {
        const headers: HttpHeaders = {
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` } : undefined),
        };

        return this.request<GetApiKeysResponseDto>({
            url: '/api-keys',
            method: 'GET',
            headers,
        }, opts?.responseOpts);
    };

}
