// tslint:disable
/**
 * msdoc server API
 * The msdoc server API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts } from '../runtime';

/**
 * no description
 */
export class DefaultApi extends BaseAPI {

    /**
     */
    appControllerGetHello(): Observable<void>
    appControllerGetHello(opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    appControllerGetHello(opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        return this.request<void>({
            url: '/',
            method: 'GET',
        }, opts?.responseOpts);
    };

}
