// tslint:disable
/**
 * msdoc server API
 * The msdoc server API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    GetServiceGroupResponse,
} from '../models';

/**
 * no description
 */
export class ServiceGroupsApi extends BaseAPI {

    /**
     */
    serviceGroupsControllerGetAllGroups(): Observable<GetServiceGroupResponse>
    serviceGroupsControllerGetAllGroups(opts?: OperationOpts): Observable<AjaxResponse<GetServiceGroupResponse>>
    serviceGroupsControllerGetAllGroups(opts?: OperationOpts): Observable<GetServiceGroupResponse | AjaxResponse<GetServiceGroupResponse>> {
        const headers: HttpHeaders = {
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` } : undefined),
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` } : undefined),
        };

        return this.request<GetServiceGroupResponse>({
            url: '/service-groups',
            method: 'GET',
            headers,
        }, opts?.responseOpts);
    };

}
