import { GetServiceDocResponse } from 'msadoc-client';

const allServiceDocs: GetServiceDocResponse[] = [
  {
    name: 'WebClient',
    group: 'frontend',
    tags: ['app=ods'],
    repository: 'https://github.com/jvalue/ods.git',
    taskBoard: 'https://github.com/jvalue/ods/projects',
    consumedAPIs: [
      '/extractions/config',
      '/extractions/execution-stats',
      '/transformation/configs',
      '/transformation/execution-stats',
      '/load/configs',
      '/load/execution-stats',
      '/notifications/configs',
      '/notifications/execution-stats',
      '/query/graphql',
      '/query/restful',
    ],
    deploymentDocumentation:
      'https://github.com/jvalue/ods/tree/main/deployment',
    responsibles: ['schwarz@group.riehle.org'],
    responsibleTeam: 'jvalue-core',
    creationTimestamp: '2022-12-16T13:56:47.727Z',
    updateTimestamp: '2022-12-16T14:00:22.610Z',
  },
  {
    name: 'ExtractionService',
    group: 'backend.etl.extract',
    tags: ['app=ods'],
    repository: 'https://github.com/jvalue/ods.git',
    taskBoard: 'https://github.com/jvalue/ods/projects',
    providedAPIs: ['/extractions/config', '/extractions/execution-stats'],
    subscribedEvents: ['extraction.execution.triggered'],
    publishedEvents: [
      'extraction.config.created',
      'extraction.config.updated',
      'extraction.config.deleted',
      'extraction.execution.success',
      'extraction.execution.failure',
    ],
    deploymentDocumentation:
      'https://github.com/jvalue/ods/tree/main/deployment',
    responsibles: ['schwarz@group.riehle.org'],
    responsibleTeam: 'jvalue-core',
    creationTimestamp: '2022-12-16T13:56:48.744Z',
    updateTimestamp: '2022-12-16T14:00:51.493Z',
  },
  {
    name: 'SchedulerService',
    group: 'backend.etl.extract',
    tags: ['app=ods'],
    repository: 'https://github.com/jvalue/ods.git',
    taskBoard: 'https://github.com/jvalue/ods/projects',
    providedAPIs: ['/scheduler/tasks'],
    subscribedEvents: [
      'extraction.config.created',
      'extraction.config.updated',
      'extraction.config.deleted',
    ],
    publishedEvents: ['extraction.execution.tiggered'],
    developmentDocumentation:
      'https://github.com/jvalue/ods/blob/main/scheduler/README.md',
    deploymentDocumentation:
      'https://github.com/jvalue/ods/tree/main/deployment',
    responsibles: ['schwarz@group.riehle.org'],
    responsibleTeam: 'jvalue-core',
    creationTimestamp: '2022-12-16T13:56:49.570Z',
    updateTimestamp: '2022-12-16T14:00:52.661Z',
  },
  {
    name: 'LoadService',
    group: 'backend.etl.load',
    tags: ['app=ods'],
    repository: 'https://github.com/jvalue/ods.git',
    taskBoard: 'https://github.com/jvalue/ods/projects',
    providedAPIs: ['/load/configs', '/load/execution-stats'],
    subscribedEvents: [
      'transformation.config.created',
      'transformation.config.updated',
      'transformation.config.deleted',
      'transformation.execution.success',
      'transformation.execution.failure',
    ],
    publishedEvents: [
      'load.config.created',
      'load.config.updated',
      'load.config.deleted',
      'load.execution.success',
      'load.execution.failure',
    ],
    deploymentDocumentation:
      'https://github.com/jvalue/ods/tree/main/deployment',
    responsibles: ['schwarz@group.riehle.org'],
    responsibleTeam: 'jvalue-core',
    creationTimestamp: '2022-12-16T13:56:52.553Z',
    updateTimestamp: '2022-12-16T13:58:07.149Z',
  },
  {
    name: 'NotificationService',
    group: 'backend',
    tags: ['app=ods'],
    repository: 'https://github.com/jvalue/ods.git',
    taskBoard: 'https://github.com/jvalue/ods/projects',
    providedAPIs: ['/notifications/configs', '/notifications/execution-stats'],
    subscribedEvents: ['load.execution.success', 'load.execution.failure'],
    publishedEvents: [
      'notification.config.created',
      'notification.config.updated',
      'notification.config.deleted',
      'notification.execution.success',
      'notification.execution.failure',
    ],
    deploymentDocumentation:
      'https://github.com/jvalue/ods/tree/main/deployment',
    responsibles: ['schwarz@group.riehle.org'],
    responsibleTeam: 'jvalue-core',
    creationTimestamp: '2022-12-16T13:56:54.131Z',
    updateTimestamp: '2022-12-16T13:58:08.297Z',
  },
  {
    name: 'RestfulQueryService',
    group: 'backend.etl.load.query',
    tags: ['app=ods'],
    repository: 'https://github.com/jvalue/ods.git',
    taskBoard: 'https://github.com/jvalue/ods/projects',
    providedAPIs: ['/query/restful'],
    subscribedEvents: [
      'loading.config.created',
      'loading.config.updated',
      'loading.config.deleted',
      'loading.execution.success',
      'loading.execution.failure',
    ],
    deploymentDocumentation:
      'https://github.com/jvalue/ods/tree/main/deployment',
    responsibles: ['schwarz@group.riehle.org'],
    responsibleTeam: 'jvalue-core',
    creationTimestamp: '2022-12-16T13:56:56.288Z',
    updateTimestamp: '2022-12-16T13:58:09.287Z',
  },
  {
    name: 'GraphQlQueryService',
    group: 'backend.etl.load.query',
    tags: ['app=ods'],
    repository: 'https://github.com/jvalue/ods.git',
    taskBoard: 'https://github.com/jvalue/ods/projects',
    providedAPIs: ['/query/graphql'],
    subscribedEvents: [
      'loading.config.created',
      'loading.config.updated',
      'loading.config.deleted',
      'loading.execution.success',
      'loading.execution.failure',
    ],
    deploymentDocumentation:
      'https://github.com/jvalue/ods/tree/main/deployment',
    responsibles: ['schwarz@group.riehle.org'],
    responsibleTeam: 'jvalue-core',
    creationTimestamp: '2022-12-16T13:56:57.659Z',
    updateTimestamp: '2022-12-16T13:58:10.360Z',
  },
  {
    name: 'TransformationService',
    group: 'backend.etl.transform',
    tags: ['app=ods'],
    repository: 'https://github.com/jvalue/ods.git',
    taskBoard: 'https://github.com/jvalue/ods/projects',
    providedAPIs: [
      '/transformation/configs',
      '/transformation/execution-stats',
    ],
    subscribedEvents: [
      'extraction.config.created',
      'extraction.config.updated',
      'extraction.config.deleted',
      'extraction.execution.success',
      'extraction.execution.failure',
    ],
    publishedEvents: [
      'transformation.execution.success',
      'transformation.execution.failure',
      'transformation.config.created',
      'transformation.config.updated',
      'transformation.config.deleted',
    ],
    developmentDocumentation:
      'https://github.com/jvalue/ods/blob/main/transformation/README.md',
    deploymentDocumentation:
      'https://github.com/jvalue/ods/tree/main/deployment',
    responsibles: ['schwarz@group.riehle.org'],
    responsibleTeam: 'jvalue-core',
    creationTimestamp: '2022-12-16T13:56:51.462Z',
    updateTimestamp: '2022-12-16T13:59:32.151Z',
  },
];

export const ServiceDocsMockData = {
  allServiceDocs: allServiceDocs,
};
