// tslint:disable
/**
 * msdoc server API
 * The msdoc server API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    CreateServiceDocRequestExtensionsValueOneOfInner,
} from './';

/**
 * @type CreateServiceDocRequestExtensionsValue
 * @export
 */
export type CreateServiceDocRequestExtensionsValue = Array<CreateServiceDocRequestExtensionsValueOneOfInner> | boolean | number | string;
