// tslint:disable
/**
 * msdoc server API
 * The msdoc server API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CreateApiKeyResponseDto
 */
export interface CreateApiKeyResponseDto {
    /**
     * @type {number}
     * @memberof CreateApiKeyResponseDto
     */
    id: number;
    /**
     * @type {string}
     * @memberof CreateApiKeyResponseDto
     */
    keyName: string;
    /**
     * @type {string}
     * @memberof CreateApiKeyResponseDto
     */
    creationTimestamp: string;
    /**
     * @type {string}
     * @memberof CreateApiKeyResponseDto
     */
    apiKey: string;
}
