// tslint:disable
/**
 * msdoc server API
 * The msdoc server API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CreateServiceDocRequest
 */
export interface CreateServiceDocRequest {
    /**
     * @type {string}
     * @memberof CreateServiceDocRequest
     */
    name: string;
    /**
     * @type {Array<string>}
     * @memberof CreateServiceDocRequest
     */
    consumedAPIs: Array<string>;
    /**
     * @type {Array<string>}
     * @memberof CreateServiceDocRequest
     */
    providedAPIs: Array<string>;
    /**
     * @type {Array<string>}
     * @memberof CreateServiceDocRequest
     */
    producedEvents: Array<string>;
    /**
     * @type {Array<string>}
     * @memberof CreateServiceDocRequest
     */
    consumedEvents: Array<string>;
    /**
     * @type {string}
     * @memberof CreateServiceDocRequest
     */
    repository: string;
    /**
     * @type {string}
     * @memberof CreateServiceDocRequest
     */
    taskBoard: string;
    /**
     * @type {string}
     * @memberof CreateServiceDocRequest
     */
    developmentDocumentation: string;
    /**
     * @type {string}
     * @memberof CreateServiceDocRequest
     */
    deploymentDocumentation: string;
    /**
     * @type {string}
     * @memberof CreateServiceDocRequest
     */
    apiDocumentation: string;
    /**
     * @type {string}
     * @memberof CreateServiceDocRequest
     */
    responsibleTeam: string;
    /**
     * @type {Array<string>}
     * @memberof CreateServiceDocRequest
     */
    responsibles: Array<string>;
}
