// tslint:disable
/**
 * msdoc server API
 * The msdoc server API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    GetServiceDocResponse,
} from './';

/**
 * @export
 * @interface ListServiceDocResponse
 */
export interface ListServiceDocResponse {
    /**
     * @type {Array<GetServiceDocResponse>}
     * @memberof ListServiceDocResponse
     */
    serviceDocs: Array<GetServiceDocResponse>;
}
