// tslint:disable
/**
 * msdoc server API
 * The msdoc server API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface LoginRequestDto
 */
export interface LoginRequestDto {
    /**
     * @type {string}
     * @memberof LoginRequestDto
     */
    username: string;
    /**
     * @type {string}
     * @memberof LoginRequestDto
     */
    password: string;
}
